### ISSUE TITLE
Lots of "Too many open files - /usr/bin/phantomjs" errors

### ISSUE THREAD

**Issue by Hainish** [EFForg/congress-forms#43]
<pre>   Too many open files - /usr/bin/phantomjs
["/home/congressforms/congress-forms/app/models/congress_member.rb:52:in `rescue in fill_out_form'", "/home/congressforms/congress-forms/app/models/congress_member.rb:39:in `fill_out_form'", "/home/congressforms/congress-forms/app/helpers/form_fill_handler.rb:15:in `block in create_thread'"]</pre>

Getting a lot of these errors.

**Comment by Hainish** [comment]
@gcosta: still encountering this?  If so, please create a new issue

**Comment by j-ro** [comment]
we're generally ok -- running about 10 instances in a pool, so have enough capacity.
