### ISSUE TITLE
SSL Handshake errors on house.gov servers recently?

### ISSUE THREAD

**Issue by j-ro** [EFForg/congress-forms#49]
We just fixed an issue that may be affecting others...

We had this all working well, successfully filling out forms on house.gov. Today, however, we're getting things like:

```
2.1.2 :027 >   session.visit "https://amodei.house.gov/"
 => {"status"=>"fail"}
```

It seems to be correlated with SSL -- http sites work fine, and we see errors like this looking further:

```
39.592689 23.218.140.161 -> 10.226.91.215 SSLv3 73 Alert (Level: Fatal, Description: Handshake Failure)
```

We didn't update any code between last week and this, but maybe something changed on house.gov to cause failure. 

anyway, we've updated some settings and it works again:

```
if driver == :poltergeist
      Capybara.register_driver :poltergeist do |app|
       Capybara::Poltergeist::Driver.new(app, :phantomjs_options => ['--ssl-protocol=TLSv1'])
      end
    end
    session = Capybara::Session.new(driver, :ignore_ssl_errors => true)
```

Maybe this will helps others.

**Comment by Hainish** [comment]
We now explicitly state TLSv1, for phantomjs 1.9.7 compatability.  Eventually we may want to remove this.
